### ISSUE TITLE
Iteration 0

### ISSUE THREAD

**Issue by ianterrell** [erikamaker/war-paint#1]
Okay, let's get started I suppose! 

There's a concept called "Iteration 0" that means "working software that doesn't really do anything". It means everything is set up. I think for our iteration 0 we might want:

- Ruby setup
   - [x] Ruby specific `.gitignore`
   - [x] `.ruby-version` for version management
- Dependency management
   - [x] `Gemfile` with our dependencies
   - [x] `Gemfile.lock` from above
- Test suite
   - [x] A placeholder test suite such that `rake test` runs
- App
   - [x] Some `src/main.rb` that outputs hello world, perhaps via `rake run`

It might be helpful for learning to work on branches and leverage PRs within GitHub to get work back into `main`.

After Iteration 0 is merged in, or even concurrently with it, we can sketch out features that might make up iteration 1. From my point of view a good path for software development is to always keep `main` in a working state, and work on small well defined iterations.

I think with our experience differential it's difficult for me to know how to proceed — what would you like?

**Comment by ianterrell** [comment]
Also, I imagine some parts of what I wrote above could bring up questions — please ask!

**Comment by erikamaker** [comment]
> Ruby specific .gitignore

Is this what we're looking for? https://github.com/github/gitignore/blob/main/Ruby.gitignore 

>  .ruby-version for version management

Sorry if this is a total beginner's question but: does this mean supplying the most Recent version of Ruby with the source code, for computers that don't currently have it? 

> Gemfile with our dependencies ... Gemfile.lock from above

https://medium.com/never-hop-on-the-bandwagon/gemfile-and-gemfile-lock-in-ruby-65adc918b856#:~:text=A%20Gemfile%20is%20a%20file,of%20these%20gems%20to%20use.

I kinda sorta get this, but I think I need to study more on what a gem IS (I know how to download and use them, currently, but only superficially). I used this article to try and wrap my head around the concept and it's a little iffy for me still. 

> Test suite ... A placeholder test suite such that rake test runs

I've heard of `rake` but haven't actually learned about it yet. It doesn't look like it's in the textbook until Chapter 14, so I want to make sure I'm ready for this concept. What do you recommend I do to grasp enough for our purposes? 

> It might be helpful for learning to work on branches and leverage PRs within GitHub to get work back into main.

I'm going to focus on becoming more fluent with GitHub this week. Is this referring, at least in part, to pull requests? 




If you'd like, I think I can at least tackle Ruby Setup for our project, in addition to practicing my GitHub skills. Let me know if you think there's a better way for me to help first!

**Comment by ianterrell** [comment]
> Is this what we're looking for? https://github.com/github/gitignore/blob/main/Ruby.gitignore

Yes, it is. In general most programming languages have a suite of files that get created that should not live in source control. Those get ignored. GitHub maintains a nice collection of defaults per language or framework; that file tells git what not to check in.

> Considering these tasks, I think there are some I need to learn more about first.

Welcome to working on software with a team! The rules are a little different and there are more things to know for sure. 😆

> I've heard of rake but haven't actually learned about it yet. It doesn't look like it's in the textbook until Chapter 14, so I want to make sure I'm ready for this concept. What do you recommend I do to grasp enough for our purposes?

I would skim Chapters 14 and 15; at least, the sections titled `Using the Rake Build Tool` and `Using Bundler to Manage Groups of Gems`. After that, the setup is maybe non-obvious at the beginning but I can help, and then usage is trivially simple.

> > `.ruby-version`
>
> Sorry if this is a total beginner's question but: does this mean supplying the most Recent version of Ruby with the source code, for computers that don't currently have it?

No. That's possible (see https://github.com/pmq20/ruby-packer and presumably other tools), but I have not done so before or yet had the need to do so.

`.ruby-version` is just a file that `rbenv` creates when you set `rbenv local <version>` so that it knows to use that version. It may be able to read Gemfile Ruby declarations now... but I've usually had `.ruby-version` stick around.

Generally the purpose of that file — and the Gemfile, and Gemfile.lock — is to make sure that you and I are working with the same stuff!

If you run something and it's broken and I run it and it works, who's right? It's the same source code, so how are we even in that situation? Well, there's the program source code and then the program environment: the version or Ruby and the versions of the gems, and the operating system, and the installed libraries, and other installed software, etc, etc.

It gets a lot easier to manage when you make sure that we are each on the same version of Ruby with the same versions of the gems we use. _Generally_ the rest is unimportant if you stick with pure Ruby, but also you only get so far with pure Ruby. Many Ruby gems are actually written in C and some depend on C libraries! The rabbit hole goes forever.

> I'm going to focus on becoming more fluent with GitHub this week. Is this referring, at least in part, to pull requests?

Eeeep, yes, I wrote "PR" without even thinking about defining it. Yes, PR = pull request. You should read about branching, and it's a good habit to perform your work in branches other than `main`. You'll push up your work to another branch and then create a pull request to get that work into `main`. The PR is a useful GitHub tool to review code and talk about it and figure out what we want it to be before it "lands" in the main branch. 

A concrete recommendation might be to find a project you like on GitHub and look at their PRs (open and closed) to get a sense of how they run things. We'll be informal, but they're good skills to practice.

> If you'd like, I think I can at least tackle Ruby Setup for our project, in addition to practicing my GitHub skills?

Sure! Why don't you work to issue a PR that adds `.ruby-version` and `.gitignore`. I'll do the same for setting up Bundler and Rake.

**Comment by erikamaker** [comment]
Thank you for getting us started! I'm aiming to do everything from the command line that I can. I started by cloning the repository including the changes you made / I merged: 


```
erikamaker@erikas-computer:~$ git clone https://github.com/erikamaker/war-paint.git
Cloning into 'war-paint'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
Receiving objects: 100% (22/22), 4.57 KiB | 1.52 MiB/s, done.
Resolving deltas: 100% (1/1), done.
remote: Total 22 (delta 1), reused 14 (delta 0), pack-reused 0

```

After, I created the .gitignore file and verified its contents: 


```
erikamaker@erikas-computer:~$ cd war-paint/
erikamaker@erikas-computer:~/war-paint$ touch .gitignore
erikamaker@erikas-computer:~/war-paint$ code .gitignore 
erikamaker@erikas-computer:~/war-paint$ cat .gitignore
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
# .env

# Ignore Byebug command history file.
.byebug_history

## Specific to RubyMotion:
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/

## Specific to RubyMotion (use of CocoaPods):
#
# We recommend against adding the Pods directory to your .gitignore. However
# you should judge for yourself, the pros and cons are mentioned at:
# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
#
# vendor/Pods/

## Documentation cache and generated files:
/.yardoc/
/_yardoc/
/doc/
/rdoc/

## Environment normalization:
/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files since the code is
# intended to run in multiple environments; otherwise, check them in:
# Gemfile.lock
# .ruby-version
# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
.rvmrc

# Used by RuboCop. Remote config files pulled in from inherit_from directive.
```

At this point I should let you know that I'm following instructions from the Git Documentation. I read that my next step was to push my changes, but I got this error.

I followed the link in the error but it wasn't super helpful, so I Googled my way to a solution that requires generating a token. I generated and secured one (it's good for 90 days), but I'm not sure how to use it to push changes. What would you do in this situation? 


```
erikamaker@erikas-computer:~/war-paint$ git push https://github.com/erikamaker/war-paint.git main
Username for 'https://github.com': erikamaker
Password for 'https://erikamaker@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/erikamaker/war-paint.git/'
```

I hope I didn't break something already!

**Comment by ianterrell** [comment]
> I hope I didn't break something already!

You can't really; not super easily at least. Try not to force push to `main` and everything will always work out fine; and even if you do and it's broken, we each have local copies and ref logs. `git` is far more forgiving than people realize, once you get to know it, so don't worry about breaking anything.

> What would you do in this situation?

Well I've debugged these situations a million times, so my path would probably be different than yours. Still, if you were a junior developer sitting in the office I'd walk you through the setup with the following.

---

You've been pushing to GitHub without issue for your other projects, so I expect that you have it set up to work over SSH. 

https://docs.github.com/en/authentication/connecting-to-github-with-ssh

I expect that if you `ls ~/.ssh` you'll see a key pair, and `cat ~/.ssh/known_hosts` will show `github.com` in there.

Now you'll want to make sure you have your local repo set up with a remote pointing to the GitHub one, over ssh. It should look like this:

```
❯ git remote -v
origin	git@github.com:erikamaker/war-paint.git (fetch)
origin	git@github.com:erikamaker/war-paint.git (push)
```

If it doesn't look like that, you'll want to remove whatever is there and add `origin` to your remotes with that address.

`git remote --help` for more instructions.

Afterward, `git fetch`.

---

Separately, you'll likely want to start learning about branching. This is practice and not strictly necessary, but will start developing good habits and skills.

```
❯ git branch
* main
```

You'll want to do your work on another branch:

```
❯ git checkout -b chore/gitignore
Switched to a new branch 'chore/gitignore'
❯ git branch
* chore/gitignore
  main
```

Then from there (assuming HEAD is your most recent commit still), push that up:

```
git push -u origin chore/gitignore
```

From there, the GitHub website will prompt you to create a pull request.

Then you'll probably want to set your `main` back to what it was before that, so that only the branch has the commit you're working on. 

```
git branch -f main origin/main
```

You should do `--help` for each of those commands to check the options: `git push --help`, etc.

**Comment by erikamaker** [comment]
> Try not to force push to main 

I looked up what this phrase means and found there's a specific git command for forcing changes to the commit history. Is that right? 

> You've been pushing to GitHub without issue for your other projects, so I expect that you have it set up to work over SSH.

On my landing-page project, I initially started by working in the command line. I was able to `git init` on the local directory, add every file to the online repo, and had began committing changes from the terminal without issue... for a few days. At that point, the terminal would not throw any errors or warnings after a change (working tree clean), but nothing would update on the online repo. The same thing happened with another one of my local repositories. I concluded that I didn't know what I was doing. I was afraid that I'd made a mistake and, out of anxiety that I might fully break something and lose all my work, I began using the website to commit changes instead. 

> Now you'll want to make sure you have your local repo set up with a remote pointing to the GitHub one, over ssh. 

Done! I also followed your subsequent steps but got stuck at the point where I should switch back from chore to origin main. This error occurred: 


```
erikamaker@erikas-computer:~/war-paint/test$ git branch -f main origin/main
fatal: not a valid object name: 'origin/main'
```

Additionally, on our repo, I tried to look for website prompts but didn't see any. I don't see anything that I can merge, but it recognizes the .gitignore file that I added. I added a screenshot below. Let me know if that's not what this image actually indicates.

![image](https://user-images.githubusercontent.com/118931925/226676628-b149109c-3961-4731-a3c2-dd8ee1ad2ee7.png)

Because all that said, I still don't see the .gitignore file in our war-paint repo yet. I'm going to keep learning about branch management and see if I can figure out where I went wrong. Thank you for your feedback!

**Comment by ianterrell** [comment]
>> Try not to force push to main
>
>I looked up what this phrase means and found there's a specific git command for forcing changes to the commit history. Is that right?

That's correct. Git maintains a history of commits in a tree type data structure, where each commit has one or more parents. It is easiest to collaborate when shared branches don't change "out from underneath" a collaborator.

e.g. if `main` goes `A B C` and we both have a copy of it, then we both can easily work on top of `C`. But if I were to, say, _overwrite_ `A B C` with `A E F` then you think it's `A B C` and I think it's `A E F` and now we're working from two different places.

Additionally, if you try to push up `D` which relies on `C`, if GitHub thinks the last commit is `F`, it won't like that much and won't let you push until you sync up. And syncing up can get confusing when you're new to git.

Some people internalize that rule as _never force push_ or even _never rewrite history_. Those are both too strict. I would suggest internalizing it eventually as _don't force push to a shared branch without knowing what you are doing and why and communicating with your team_. 

At the beginning, _don't force push_ is a reasonable substitute, knowing you'll relax it later as you learn more about git.

```
erikamaker@erikas-computer:~/war-paint/test$ git branch -f main origin/main
fatal: not a valid object name: 'origin/main'
```

You may have needed to fetch first after repopulating your remotes. `git fetch` or `git fetch origin`. You're probably still up to date with it — hard to say. Eventually you'll probably want to do something like:

```
git checkout main
git branch -u origin/main
git reset --hard origin/main
```

You'll just want to make sure you see something like this:

```
❯ git log -10 --oneline
3d0e9e8 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #2 from erikamaker/chore/setup
b0ea322 Set up source and test suite with Rake
0bb7797 Update README.md
bbcd97b Initial commit
```

> I followed the following prompt, but I don't see anything that I can merge,

If you browse the repo main page or the pull requests page shortly after you push something to a new branch, GitHub will usually prompt you to create a PR:

<img width="1110" alt="Screenshot 2023-03-21 at 1 57 13 PM" src="https://user-images.githubusercontent.com/54963/226699475-6626e22e-9b02-4fee-91c5-ade6eda33067.png">

You can always click "New Pull Request" from the PR page which will open up this: https://github.com/erikamaker/war-paint/compare

There you can choose where to merge from and where to merge to; in your case `main` as base and `chore/gitignore` as the compare branch.

Unfortunately... we're at one of those points where the histories don't match from rewriting or other accidents. :)

<img width="1467" alt="Screenshot 2023-03-21 at 1 58 55 PM" src="https://user-images.githubusercontent.com/54963/226699962-a19b2637-1e93-4471-a2e6-97b29c5b520a.png">

It looks like your branch is entirely divorced from the existing one. Which you can see! Here's main:

<img width="508" alt="Screenshot 2023-03-21 at 2 00 12 PM" src="https://user-images.githubusercontent.com/54963/226700241-5bab5af0-d388-46c7-83f6-8439fc629405.png">

Here's your branch:

<img width="732" alt="Screenshot 2023-03-21 at 2 00 32 PM" src="https://user-images.githubusercontent.com/54963/226700324-36179892-b47e-40b7-9426-b7052439e51f.png">

Unfortunately, they have nothing in common.

Git builds up the history in order; each commit has one or more parents; clicking into a commit you can see them:

<img width="295" alt="Screenshot 2023-03-21 at 2 01 48 PM" src="https://user-images.githubusercontent.com/54963/226700665-1a56f8bc-3de9-4551-bbe6-9dfdc4d2ab8a.png">

(Also via `git show <commit or ref>`).

So `main` has A B C D and your branch has E F and GitHub says, "uh, they have nothing to do with one another, I can't merge these!".

To unstick us for now, I'm going to create a new branch where that commit is part of the tree.

```
❯ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
❯ git checkout -b chore/gitignore2
Switched to a new branch 'chore/gitignore2'
❯ git cherry-pick d82a490e83bb7534b3f627df63f49dda37a39576
[chore/gitignore2 e1de9f7] Add .gitignore file
 Author: Erika Maker <erikamaker@outlook.com>
 Date: Tue Mar 21 12:16:06 2023 -0400
 1 file changed, 56 insertions(+)
 create mode 100644 .gitignore
❯ git push -u origin chore/gitignore2
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.14 KiB | 1.14 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote:
remote: Create a pull request for 'chore/gitignore2' on GitHub by visiting:
remote:      https://github.com/erikamaker/war-paint/pull/new/chore/gitignore2
remote:
To github.com:erikamaker/war-paint.git
 * [new branch]      chore/gitignore2 -> chore/gitignore2
branch 'chore/gitignore2' set up to track 'origin/chore/gitignore2'.
```

Each part of that is worth making sure you understand.

Now GitHub prompts me to create a PR:

<img width="1100" alt="Screenshot 2023-03-21 at 2 04 20 PM" src="https://user-images.githubusercontent.com/54963/226701249-e1228680-838d-4dfa-b8d9-b4e70775e7c3.png">

But I will let you create one via https://github.com/erikamaker/war-paint/compare/chore/gitignore2?expand=1

---

> At that point, the terminal would not throw any errors or warnings after a change (working tree clean), but nothing would update on the online repo. 

It's hard to say what's happening here, but it sounds like the changes didn't get pushed up.

> The same thing happened with another one of my local repositories. I concluded that I didn't know what I was doing. I was afraid that I'd made a mistake and, out of anxiety that I might fully break something and lose all my work, I began using the website to commit changes instead.

Well, no time like the present to try to get it all worked out and learn everything. :)

I don't have a tutorial to recommend, but there are bound to be some good ones. I expect that everything under "Using Git" is worth reading and understanding: https://docs.github.com/en/get-started/using-git/about-git

Generally, the workflow will be something like this:

```
# Check your current status
# type this all the time, make sure your state is what you expect
git status 

# Get up to date with latest changes
git checkout main
git pull # this updates main from the tracked branch, which should be origin/main (GitHub's copy)

# check out a new branch for your work:
git checkout -b feature/my-feature
# do your work, commit and push your files
git add .
git commit
git push -u origin feature/my-feature

# create a PR
# update it with changes
git add .
git commit
git push

# get it merged in

# rinse repeat
git checkout main
git pull
```

There's a lot more and a lot of variety with how people arrange their workflow, but that's the most basic one that you can start with.

---

Generally, if you run into too much trouble just copy all of the relevant terminal commands and output and we can work it out.

**Comment by erikamaker** [comment]
Thanks for the insight. I merged the .gitignore file, though I don't quite understand how you were able to stage that for me! I'll keep learning about branch management. After I get .ruby-version up, and assuming success, I'm going to study from the Ruby text for an hour or so. 

```
erikamaker@erikas-computer:~/war-paint$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
😄

**Comment by erikamaker** [comment]
# _Git Crash Course Progress_

# Branch (to check what branch I'm in) 


```
erikamaker@erikas-computer:~/war-paint$ git branch test
erikamaker@erikas-computer:~/war-paint$ git branch
  chore/gitignore
  chore/ruby-version
* main
  test
```

# branch -d <filename> 

This deletes a branch. Be very careful when doing this. 

```
erikamaker@erikas-computer:~/war-paint$ git -d gitignore

```


# Checkout (switch to another branch) 


```
erikamaker@erikas-computer:~/war-paint$ git branch
  chore/gitignore
  chore/ruby-version
  main
* test
```

Note: it's normal to lose the files that were in the branch you were previously working in. They're still there, you're just not in that branch anymore. It's part of how git branches work. To get the files that you temporarily lose when changing branches, you simply have to merge so that the current branch now shares those files. 



# Merge

```
erikamaker@erikas-computer:~/war-paint$ git checkout chore/ruby-version
Switched to branch 'chore/ruby-version'
Your branch is up to date with 'origin/chore/ruby-version'.
erikamaker@erikas-computer:~/war-paint$ ls
bin  Gemfile  Gemfile.lock  lib  LICENSE  Rakefile  README.md  test
erikamaker@erikas-computer:~/war-paint$ git branch
  chore/gitignore
* chore/ruby-version
  main
  test
erikamaker@erikas-computer:~/war-paint$ rbenv local 3.2.1
erikamaker@erikas-computer:~/war-paint$ ls
bin  Gemfile  Gemfile.lock  lib  LICENSE  Rakefile  README.md  test
erikamaker@erikas-computer:~/war-paint$ git add .
erikamaker@erikas-computer:~/war-paint$ git commit -a -m 'Commit ruby-version'
[chore/ruby-version 33e0875] Commit ruby-version
 1 file changed, 1 insertion(+)
 create mode 100644 .ruby-version
erikamaker@erikas-computer:~/war-paint$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
erikamaker@erikas-computer:~/war-paint$ git merge chore/ruby-version 
Updating 180a8ef..33e0875
Fast-forward
 .ruby-version | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 .ruby-version
```

# Branching and the File System


There are many valid ways to manage a branching strategy. The current exercise is redirecting me to the github git tutorial website, and asks me to complete the section on git branches. My 15 minute break is about up, so I'm going to jump back into this on lunch. #
